sudo: required

language: go
go:
  - "1.11"

env:
  - GO111MODULE=on

before_install:
  - go get -u github.com/mattn/goveralls

script:
  - go test -v -cover -race -coverprofile=./coverage.out ./...
  - ./ci/coverage.sh